name: Generate man pages

on:
  push:
    paths:
      - "Base/usr/share/man/**"
      - "Meta/Websites/gelassenheitbs.github.io/Benutzerhandbuch-Internetseite/**"

jobs:
  convert_using_pandoc:
    runs-on: ubuntu-20.04
    if: always() && github.repository == 'GelassenheitBS/Gelassenheit' && github.ref == 'refs/heads/master' && never() # BEHEBEMICH: Generiere ein neues Token, und baue es hier ein.
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.13'
      - name: Actually build website
        run: ./Meta/build-manpages-website.sh
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          git-config-name: BuggieBot
          git-config-email: buggiebot@serenityos.org
          branch: master
          repository-name: GelassenheitBS/manpages-website
          token: ${{ secrets.BUGGIEBOT }}
          folder: output
